language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: ZqvGO/HQMCakD4kchggGotQD6gmoXDVxtTAz9izJlImL6ZRZ1EXtaedwBK2cdHCacxcN0luSHSli7kbViYadQrZb5Tm3pUuqmmaCvLKSKyGmLCzS2IWIvZufaOYoKDGK6oIaiPdiLBkOepI/3lwpCcCk2vz45tirvqesDwG145KLN9zaqH3/nZX1dUaFX9kOvpZTVXrzDZIaX22lC7hU5MpbVC1NUIRGh9Y/8uehMYTbujCP9tluDYGZ6UFkCbMQx56wkiQ7+xoEGAFWCtMRqhEqYx3AcUHYvOHWm377Vg29KXRZwhAbgYSQFBDk65uv5Dklvs0mKfof6YwAqpCkGxioXpFlP+bt7tjwwKIxS8/J30fggPWFwxz0PF57bU/x0ZQOE4BzrUtqsOVDCvgXAYpVaqSKbRL4acZOEG17GnD1vlX6kPtKLB5ap4I3Ym6jxLb2ia5DOZmAFFnKW5qpFQcJXWoapAwftoVIeaYGiJCCIOugdRk76/PFmyNVcrCYgh+u3qobWcZwXGBZlFM5BwfKlbF5Pymvt/oNoX8pwJkcgE05Sn5CJqi9Od2ngj/CguHuESQgk1V5hR3BqGbaQAttb59/FBeEP4w2UiupDLz2G0zxHFP7W6DWD5tywF2TJJ/+MjnwCKyOAP5TSmmPDB39ieX4zM65FhX8k4plMTY=
  app: trviad1
